### ISSUE TITLE
Support for other C++ engines

### ISSUE THREAD

**Issue by Moguri** [heroiclabs/nakama-unreal#1]
The [original issue](https://github.com/heroiclabs/nakama/issues/7) for creating an Unreal client in the main Nakama repo mentioned compatibility for other C++ engines. Is this still a plan for this repo? If not, this report can be closed, and I can open a new report on the main Nakama repo.

**Comment by Renanse** [comment]
Hypothetically, we are compatible with that idea; the code was written with the goal to keep the Unreal API out of all classes except where necessary (NUnrealTransport and NWebSocket for example.)  Until we actually try to use this with a second C++ based engine however, it is an open question as to how successful this effort was. :)

**Comment by janimm** [comment]
We have successfully modified Nakama-Unreal to our in-house cross platform C++ environment. Basically what you need to do is.

- Use libwebsockets
- Replace all type references of 'uint8, uint16, int16 etc' to 'uint8_t' and so on. Or alternatively typedef those missing basic types.
- There are couple of references to Unreal Guid, and UtcNow timestamps which need to be replaced.
- The replacement class for NUnrealTransport need to be written. For this you need an HTTP connection provider. The 'socket' part of this class can be reused.
- Replacement NUnrealTransport::Tick must be called periodically.
- NWebSocket uses Unreal TArray as dynamic byte storage and that needs to be replaced. Otherwise this class works as-is with libwebsockets.

Thats all I remember from top of my head. Hope this helps.

**Comment by Renanse** [comment]
Is there a chance you could open a pull request for this and contribute back?

**Comment by janimm** [comment]
We have replaced Unreal bits with our own, and merging those would not make any sense. I'll take a look at some point to help bring Nakama-Unreal at least couple of steps closer to generic C++, while retaining Unreal compatibility.

**Comment by trueleowdeo** [comment]
We urgently need generic  c++ without the unreal engine bits

**Comment by trueleowdeo** [comment]
Please support generic c++ not just unreal

**Comment by novabyte** [comment]
@trueleowdeo This is something we'd like to do. Can you tell me more about what game engine you use?

**Comment by Renanse** [comment]
I've taken a stab at this in the branch genericize (b578db2cf59b645c1a2d00925fbb26ff6c439db2)  It still needs a good amount of testing, though not sure when I will get that chance.

**Comment by mofirouz** [comment]
We are working on a generic C++ client which will be the base for a new Cocos2dx and Unreal clients. This is in the works right now and we'll be open-sourcing the repo soon. 

We'd love people to give us feedback in an early access. Feel free to ping here if you want to have an early access to the repository and I can add you to it.

I'm leaving the link here for later: 
https://github.com/heroiclabs/nakama-cpp

**Comment by mofirouz** [comment]
We have a dedicated C++ client library: https://github.com/heroiclabs/nakama-cpp
You can find the guide here: https://heroiclabs.com/docs/cpp-client-guide/
