### ISSUE TITLE
Up-To-Date

### ISSUE THREAD

**Issue by Brianelvio** [heroiclabs/nakama-unreal#11]
Hi,

Just wondering if this framework is up to date and working with the latest nakama version?
We recently switched from Unity to UE4 in early stages of development and it looks like it's been a while since this got updated =)

**Comment by novabyte** [comment]
@Brianelvio We're a bit behind with the updates to client libraries since we launched the 2.0 version of the game server. Too many feature requests for the main server 😄 

We have plans to update the Unreal client but I don't have an immediate timeline. We did add HTTP/REST support to the server which could be used to integrate your own client.

**Comment by Flotea-dev** [comment]
Hello, there are any possibility to update this ??
Anyone know how to simplify connect to new Nakama 2.0 with for example C++ Blueprint under Unreal 4.20+ (not over http/rest, but on RTP) ?

**Comment by mofirouz** [comment]
@Flotea-dev This is definitely on our radar but I can't provide a timeline. If you'd like to help with this, I can provide some guidance on how to go about either updating this client, or writing a new one from scratch (most will be code generated through gRPC :))

Jump on [Gitter](https://gitter.im/heroiclabs/nakama) and message me if you'd like to help out.

**Comment by mofirouz** [comment]
I'm closing this as this is currently being tracked on #14.
