### ISSUE TITLE
Add Blueprint support for Nakama.

### ISSUE THREAD

**Issue by mofirouz** [heroiclabs/nakama-unreal#15]
To be able to publish to the Unreal Marketplace, we need to have Blueprint support.

**Comment by Renanse** [comment]
I assume you mean for Nakama 2 since the old nakama-unreal code does support blueprint?

**Comment by AlimJaffer** [comment]
@Renanse correct. We have an updated C++ client that's in early access for Nakama 2 :)

**Comment by HeadClot** [comment]
I would like to echo support for this. +1 for blueprints support in Nakama 2 :)

**Comment by RyanJEC** [comment]
Is this being worked on?

**Comment by lugehorsam** [comment]
@RyanJEC this is not being actively worked on, but it is something we would like to support in the future.

**Comment by DeoVolenteGames** [comment]
If it helps I've made a [small blueprint plugin for Nakama](https://github.com/DeoVolenteGames/nakama-bp-plugin). It's fairly limited and untested, but I intend to add more functions slowly and polish it up as I go. It may not be the best example to build off since it's more of a proof of concept than anything else, but it should work as a stop-gap for users who are getting started, or who want to use it in game jams and the like.

**Comment by lugehorsam** [comment]
This has now been added in the latest release.
