### ISSUE TITLE
Unreal Multiplayer Local Testing Users Have Same ID

### ISSUE THREAD

**Issue by spentak** [heroiclabs/nakama-unreal#18]
It might be worthy to note in docs, or better yet create some functionality in the Unreal Nakama SDK to create different IDs for local host testing.

I kept running into an issue where I couldn't deterministically set who would be host.

I came to find out that both of my local game sessions were issued the same User id.

ie In Unreal, if you set players to > 1 you can execute multiple game sessions. These users are all given the same UserId from the Nakama server.

Am I crazy or is this a real issue?

**Comment by novabyte** [comment]
Hi @spentak.

> ie In Unreal, if you set players to > 1 you can execute multiple game sessions. These users are all given the same UserId from the Nakama server.

Nakama allows you to create multiple sessions per user by design; it's a feature of the game server. Each of these sessions is uniquely identified via a {user_id, session_id, node_id} tuple. We refer to it as a presence.

> better yet create some functionality in the Unreal Nakama SDK to create different IDs for local host testing

This can already be achieved easily. You can authenticate multiple times against the server if wanted each with a generated value (probably a UUIDv4 I'd recommend) either with custom or device authentication. But as mentioned above the server already gives you a clear way to disambiguate sessions on the server without the need to signin locally multiple times as different users while you test.

I don't think this is an issue with the client sdk or the server. You can disambiguate the session for the same user ID by session ID.

**Comment by spentak** [comment]
I see. Thanks

**Comment by novabyte** [comment]
@spentak I reread your post and realized I'd assumed you use the multiplayer engine in the game server and want to disambiguate a host player in that context. But if you want to "signin" as different users locally in a single Unreal engine session I'd recommend the second option I mentioned. Hope it helps.

**Comment by spentak** [comment]
Yes. What I'm going to do is check if in development and if so generate a UUID (instead of using device ID) for each participant. For some reason I didn't take into account that the ID would be the same if im passing in the same device ID haha.
