### ISSUE TITLE
NClientInterface::getAccount() not working for non ascii characters

### ISSUE THREAD

**Issue by mgossage** [heroiclabs/nakama-unreal#45]
Repro steps:
1. Create an account
2. Using developer console change the username or display name to use accented characters. (eg. abcöäüß, also seems to fail with french, spanish and chinese characters)
3. Using NClientInterface::getAccount() get the account.
4. Using breakpoints (or similar) examine the NAccount returned in the callback
5. Non-ascii characters have been replaced by a '?'
![image](https://user-images.githubusercontent.com/24657446/105085904-599a3180-5a90-11eb-924c-e28b684570d2.png)

**Comment by lugehorsam** [comment]
Hey @mgossage, are you testing this on Windows? I was able to reproduce your issue in the Windows terminal because my system wasn't using UTF-8 as its default encoding. Once I switched to UTF-8, the issue was resolved.

(1) Go to administrative language settings
(2) Change system locale
(3) Check Beta: Use Unicode UTF-8 for worldwide language support box
(4) Restart PC

**Comment by mgossage** [comment]
Tried that, exactly the same error.
Also the question marks seem to be actual question marks and not just out of range values. I will dig some more.
![image](https://user-images.githubusercontent.com/24657446/112140201-a226b600-8bcb-11eb-9da3-f6cfc618d24d.png)

**Comment by lugehorsam** [comment]
@mgossage okay thanks for digging a bit more. I also looked at my breakpoint and saw the correct UTF-8 chars in your example.
